# Generated by Django 3.1.6 on 2021-02-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0002_auto_20210218_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
