# Generated by Django 3.1.6 on 2021-02-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_auto_20210217_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
