# Generated by Django 3.1.6 on 2021-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_auto_20210217_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
